
services:
    game:
        build:
            context: ../game
            # target: Develop # デバッグ用にビルドする
        hostname: game
        restart: always
        tty: true
        volumes:
            - ../game/src:/root/game
            - ../game/database:/game/database